// Code generated by protoc-gen-go.
// source: logmsgs.proto
// DO NOT EDIT!

/*
Package logmsgs is a generated protocol buffer package.

It is generated from these files:
	logmsgs.proto

It has these top-level messages:
	Log
	LogGroup
	LogGroupList
*/
package loghub

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Log struct {
	Time             *uint32        `protobuf:"varint,1,req,name=time" json:"time,omitempty"`
	Contents         []*Log_Content `protobuf:"bytes,2,rep,name=contents" json:"contents,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *Log) Reset()                    { *m = Log{} }
func (m *Log) String() string            { return proto.CompactTextString(m) }
func (*Log) ProtoMessage()               {}
func (*Log) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Log) GetTime() uint32 {
	if m != nil && m.Time != nil {
		return *m.Time
	}
	return 0
}

func (m *Log) GetContents() []*Log_Content {
	if m != nil {
		return m.Contents
	}
	return nil
}

type Log_Content struct {
	Key              *string `protobuf:"bytes,1,req,name=key" json:"key,omitempty"`
	Value            *string `protobuf:"bytes,2,req,name=value" json:"value,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Log_Content) Reset()                    { *m = Log_Content{} }
func (m *Log_Content) String() string            { return proto.CompactTextString(m) }
func (*Log_Content) ProtoMessage()               {}
func (*Log_Content) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0, 0} }

func (m *Log_Content) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *Log_Content) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type LogGroup struct {
	Logs             []*Log  `protobuf:"bytes,1,rep,name=logs" json:"logs,omitempty"`
	Reserved         *string `protobuf:"bytes,2,opt,name=reserved" json:"reserved,omitempty"`
	Topic            *string `protobuf:"bytes,3,opt,name=topic" json:"topic,omitempty"`
	Source           *string `protobuf:"bytes,4,opt,name=source" json:"source,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LogGroup) Reset()                    { *m = LogGroup{} }
func (m *LogGroup) String() string            { return proto.CompactTextString(m) }
func (*LogGroup) ProtoMessage()               {}
func (*LogGroup) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LogGroup) GetLogs() []*Log {
	if m != nil {
		return m.Logs
	}
	return nil
}

func (m *LogGroup) GetReserved() string {
	if m != nil && m.Reserved != nil {
		return *m.Reserved
	}
	return ""
}

func (m *LogGroup) GetTopic() string {
	if m != nil && m.Topic != nil {
		return *m.Topic
	}
	return ""
}

func (m *LogGroup) GetSource() string {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return ""
}

type LogGroupList struct {
	LogGroupList     []*LogGroup `protobuf:"bytes,1,rep,name=logGroupList" json:"logGroupList,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *LogGroupList) Reset()                    { *m = LogGroupList{} }
func (m *LogGroupList) String() string            { return proto.CompactTextString(m) }
func (*LogGroupList) ProtoMessage()               {}
func (*LogGroupList) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *LogGroupList) GetLogGroupList() []*LogGroup {
	if m != nil {
		return m.LogGroupList
	}
	return nil
}

func init() {
	proto.RegisterType((*Log)(nil), "Log")
	proto.RegisterType((*Log_Content)(nil), "Log.Content")
	proto.RegisterType((*LogGroup)(nil), "LogGroup")
	proto.RegisterType((*LogGroupList)(nil), "LogGroupList")
}

func init() { proto.RegisterFile("logmsgs.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 197 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xcc, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0xc0, 0x71, 0x9a, 0x44, 0xed, 0xce, 0xa6, 0x22, 0x73, 0x0a, 0x1e, 0xb4, 0x14, 0x84, 0x3d,
	0x45, 0xf0, 0x15, 0x3c, 0x78, 0x09, 0x78, 0xf7, 0x26, 0x75, 0x08, 0xc5, 0xb4, 0x53, 0x92, 0xb4,
	0xe0, 0xdb, 0x4b, 0xbf, 0x60, 0x6f, 0xf3, 0x1f, 0x66, 0x7e, 0x50, 0x05, 0xf6, 0x7d, 0xf2, 0xc9,
	0x8e, 0x91, 0x33, 0x37, 0x5f, 0x20, 0x1d, 0x7b, 0xd4, 0xa0, 0x72, 0xd7, 0x93, 0x29, 0x6a, 0x71,
	0xa9, 0xf0, 0x09, 0xca, 0x96, 0x87, 0x4c, 0x43, 0x4e, 0x46, 0xd4, 0xf2, 0x72, 0x7e, 0xd3, 0xd6,
	0xb1, 0xb7, 0xef, 0xdb, 0xf2, 0xf1, 0x05, 0xee, 0xf6, 0x11, 0xcf, 0x20, 0x7f, 0xe9, 0x6f, 0xfd,
	0x3b, 0x61, 0x05, 0x37, 0xf3, 0x77, 0x98, 0xc8, 0x88, 0x25, 0x9b, 0x4f, 0x28, 0x1d, 0xfb, 0x8f,
	0xc8, 0xd3, 0x88, 0x08, 0x2a, 0xb0, 0x4f, 0xa6, 0x58, 0x39, 0xb5, 0x70, 0xf8, 0x00, 0x65, 0xa4,
	0x44, 0x71, 0xa6, 0x1f, 0x23, 0xea, 0x62, 0x03, 0x32, 0x8f, 0x5d, 0x6b, 0xe4, 0x9a, 0xf7, 0x70,
	0x9b, 0x78, 0x8a, 0x2d, 0x19, 0xb5, 0x74, 0xf3, 0x0a, 0xfa, 0x00, 0x5d, 0x97, 0x32, 0x3e, 0x83,
	0x0e, 0x57, 0xbd, 0xe3, 0x27, 0x7b, 0x1c, 0xfd, 0x07, 0x00, 0x00, 0xff, 0xff, 0x2c, 0x91, 0x6b,
	0x47, 0xed, 0x00, 0x00, 0x00,
}
